"""
Accounting Router
Handles doctor revenue and compensation calculations.
"""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session

from .. import models, schemas
from .auth import get_current_user, get_db
from ..services.accounting_service import AccountingService

# Forced Reload of Accounting Module
router = APIRouter(prefix="/accounting", tags=["Accounting"])


@router.get("/doctor-revenue")
def get_doctor_revenue(
    start_date: str = Query(..., description="Start date (YYYY-MM-DD)"),
    end_date: str = Query(..., description="End date (YYYY-MM-DD)"),
    db: Session = Depends(get_db),
    current_user: schemas.User = Depends(get_current_user),
):
    """
    Get revenue generated by each doctor within a date range.
    Returns list of doctors with their treatment counts and total revenue.
    """
    service = AccountingService(db, current_user.tenant_id)
    try:
        start, end = service.parse_date_range(start_date, end_date)
    except ValueError:
        return {"doctors": [], "error": "Invalid date format"}

    doctors = service.get_doctor_revenue_analytics(start, end)
    return {"doctors": doctors}


@router.get("/doctor-details/{doctor_id}")
def get_doctor_details(
    doctor_id: int,
    start_date: str = Query(..., description="Start date (YYYY-MM-DD)"),
    end_date: str = Query(..., description="End date (YYYY-MM-DD)"),
    db: Session = Depends(get_db),
    current_user: schemas.User = Depends(get_current_user),
):
    """
    Get detailed breakdown for a specific doctor: treatments and lab orders.
    """
    service = AccountingService(db, current_user.tenant_id)
    try:
        start, end = service.parse_date_range(start_date, end_date)
    except ValueError:
        return {"error": "Invalid date format"}

    details = service.get_doctor_details_data(doctor_id, start, end)
    if not details:
        return {"error": "Doctor not found"}

    return details


@router.put("/staff-compensation/{user_id}")
def update_staff_compensation(
    user_id: int,
    commission_percent: float = 0.0,
    fixed_salary: float = 0.0,
    per_appointment_fee: float = 0.0,
    db: Session = Depends(get_db),
    current_user: schemas.User = Depends(get_current_user),
):
    """Update compensation settings for a staff member."""
    service = AccountingService(db, current_user.tenant_id)
    success = service.update_staff_compensation_settings(
        user_id, current_user, commission_percent, fixed_salary, per_appointment_fee
    )

    if not success:
        return {"error": "User not found"}

    return {"success": True, "message": "Compensation updated"}


@router.get("/staff-revenue")
def get_staff_revenue(
    start_date: str = Query(..., description="Start date (YYYY-MM-DD)"),
    end_date: str = Query(..., description="End date (YYYY-MM-DD)"),
    db: Session = Depends(get_db),
    current_user: schemas.User = Depends(get_current_user),
):
    """Get revenue for non-doctor staff (assistants, receptionists, etc.)."""
    # Note: date range logic was in original but unused for listing staff.
    # Just validating date format to keep API consistent.
    service = AccountingService(db, current_user.tenant_id)
    try:
        service.parse_date_range(start_date, end_date)
    except ValueError:
        return {"staff": [], "error": "Invalid date format"}

    staff_list = service.get_staff_list_revenue()
    return {"staff": staff_list}


@router.get("/comprehensive-stats")
def get_comprehensive_stats(
    start_date: str = Query(..., description="Start date (YYYY-MM-DD)"),
    end_date: str = Query(..., description="End date (YYYY-MM-DD)"),
    db: Session = Depends(get_db),
    current_user: schemas.User = Depends(get_current_user),
):
    """
    Get comprehensive financial statistics with automatic deductions.
    """
    service = AccountingService(db, current_user.tenant_id)
    try:
        start, end = service.parse_date_range(start_date, end_date)
    except ValueError:
        return {"error": "Invalid date format"}

    # 1. Basic Income Stats
    total_income = service.get_total_income(start, end)
    total_collected = service.get_total_collected(start, end)

    # 2. Get appointments count (needed for staff dues)
    # Using service query manually or adding a helper?
    # Let's add a quick helper or just query it here since it's simple?
    # Actually, let's keep it simple here and query.
    # But wait, we want to move logic out.
    # Let's add `get_appointments_count` to service or just use what we have.
    # Service doesn't have `get_appointments_count` yet.
    # I can query it using count on treatments.
    # 2a. Get Appointments Count (for staff dues calculation)
    total_appointments = (
        db.query(models.Treatment.id)
        .join(models.Patient, models.Treatment.patient_id == models.Patient.id)
        .filter(
            models.Patient.tenant_id == current_user.tenant_id,
            models.Patient.is_deleted == False,
            models.Treatment.date >= start,
            models.Treatment.date <= end,
        )
        .count()
    )

    # 2b. Get Unique Patients Count (for UI display)
    unique_patients_count = (
        db.query(models.Treatment.patient_id)
        .join(models.Patient, models.Treatment.patient_id == models.Patient.id)
        .filter(
            models.Patient.tenant_id == current_user.tenant_id,
            models.Patient.is_deleted == False,
            models.Treatment.date >= start,
            models.Treatment.date <= end,
        )
        .distinct()
        .count()
    )

    # 3. Dues & Expenses
    doctor_dues, total_doctor_dues = service.calculate_doctor_dues(start, end)
    staff_dues, total_staff_dues = service.calculate_staff_dues(
        start, end, total_appointments
    )

    total_expenses = service.get_total_expenses(start, end)
    total_lab_costs = service.get_total_lab_costs(start, end)

    # 4. Net Profit
    # Net Profit = Collected (Cash In) - Expenses (Cash Out)
    net_profit = (
        float(total_collected)
        - float(total_doctor_dues)
        - float(total_staff_dues)
        - float(total_expenses)
        - float(total_lab_costs)
    )

    # 5. ALL TIME Outstanding (Total Debt)
    # The user wants "Remaining" to be the actual debt, not period math.
    from ..crud import billing as billing_crud

    all_time_stats = billing_crud.get_financial_stats(db, current_user.tenant_id)
    real_outstanding = all_time_stats["outstanding"]

    return {
        "period": {"start": start_date, "end": end_date},
        "income": {
            "total_revenue": float(total_income),
            "total_collected": float(total_collected),
            "outstanding": float(real_outstanding),  # FIXED: Show actual total debt
            "total_appointments": unique_patients_count,  # Returning unique patients as requested (keeping key name compatible if frontend expects it, or better rename it)
            "unique_patients": unique_patients_count,
        },
        "deductions": {
            "doctor_dues": {"total": float(total_doctor_dues), "details": doctor_dues},
            "staff_dues": {"total": float(total_staff_dues), "details": staff_dues},
            "lab_costs": float(total_lab_costs),
            "expenses": float(total_expenses),
            "total_deductions": float(total_doctor_dues)
            + float(total_staff_dues)
            + float(total_expenses),
        },
        "net_profit": net_profit,
    }


@router.get("/salaries")
def get_salaries_status(
    month: str = Query(..., description="Month in format YYYY-MM"),
    db: Session = Depends(get_db),
    current_user: schemas.User = Depends(get_current_user),
):
    """
    Get salary payment status for all employees for a specific month.
    """
    service = AccountingService(db, current_user.tenant_id)
    try:
        return service.get_salary_status_for_month(month)
    except ValueError:
        return {"error": "Invalid month format. Use YYYY-MM"}


@router.post("/salaries")
def record_salary_payment(
    user_id: int,
    month: str = Query(..., description="Month in format YYYY-MM"),
    amount: float = 0.0,
    is_partial: bool = False,
    days_worked: int = None,
    notes: str = None,
    db: Session = Depends(get_db),
    current_user: schemas.User = Depends(get_current_user),
):
    """Record a salary payment for an employee."""
    service = AccountingService(db, current_user.tenant_id)
    result = service.process_salary_payment(
        user_id, current_user, month, amount, is_partial, days_worked, notes
    )
    if "error" in result:
        return result

    return {
        "success": True,
        "payment_id": result["payment_id"],
        "message": "تم تسجيل الدفع بنجاح",
    }


@router.delete("/salaries/{payment_id}")
def delete_salary_payment(
    payment_id: int,
    db: Session = Depends(get_db),
    current_user: schemas.User = Depends(get_current_user),
):
    """Delete/Cancel a salary payment record."""
    service = AccountingService(db, current_user.tenant_id)
    success = service.remove_salary_payment(payment_id, current_user)

    if not success:
        return {"error": "لم يتم العثور على سجل الدفع"}

    return {"success": True, "message": "تم حذف سجل الدفع"}


@router.put("/staff/{user_id}/hire-date")
def update_hire_date(
    user_id: int,
    hire_date: str = Query(..., description="Hire date in format YYYY-MM-DD"),
    db: Session = Depends(get_db),
    current_user: schemas.User = Depends(get_current_user),
):
    """Update the hire date for an employee."""
    service = AccountingService(db, current_user.tenant_id)
    success = service.update_employee_hire_date(user_id, hire_date, current_user)

    if not success:
        # success=False usually implies user not found or format error.
        # service returns False for both.
        # For better error message we might check format here or assume format error handled by helper?
        # Helper logs format error as False.
        # Let's return generic error.
        return {"error": "حدث خطأ. تأكد من وجود الموظف وصحة التاريخ (YYYY-MM-DD)"}

    return {"success": True, "message": "تم تحديث تاريخ بداية العمل"}
