"""
Accounting Router
Handles doctor revenue and compensation calculations.
"""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func

from .. import models, schemas
from ..crud import billing as billing_crud
from .auth import get_async_db
from backend.core.permissions import Permission, require_permission
from backend.core.response import success_response, StandardResponse, error_response
from ..services.accounting_service import AccountingService

# Forced Reload of Accounting Module
router = APIRouter(prefix="/accounting", tags=["Accounting"])


@router.get("/doctor-revenue", response_model=StandardResponse[dict])
async def get_doctor_revenue(
    start_date: str = Query(..., description="Start date (YYYY-MM-DD)"),
    end_date: str = Query(..., description="End date (YYYY-MM-DD)"),
    db: AsyncSession = Depends(get_async_db),
    current_user: schemas.User = Depends(require_permission(Permission.FINANCIAL_READ)),
):
    """
    Get revenue generated by each doctor within a date range.
    Returns list of doctors with their treatment counts and total revenue.
    """
    service = AccountingService(db, current_user.tenant_id)
    try:
        start, end = service.parse_date_range(start_date, end_date)
    except ValueError:
        return error_response(message="Invalid date format", details={"doctors": []})

    doctors = await service.get_doctor_revenue_analytics(start, end)
    return success_response(data={"doctors": doctors}, message="Doctor revenue retrieved successfully")


@router.get("/doctor-details/{doctor_id}", response_model=StandardResponse[dict])
async def get_doctor_details(
    doctor_id: int,
    start_date: str = Query(..., description="Start date (YYYY-MM-DD)"),
    end_date: str = Query(..., description="End date (YYYY-MM-DD)"),
    db: AsyncSession = Depends(get_async_db),
    current_user: schemas.User = Depends(require_permission(Permission.FINANCIAL_READ)),
):
    """
    Get detailed breakdown for a specific doctor: treatments and lab orders.
    """
    service = AccountingService(db, current_user.tenant_id)
    try:
        start, end = service.parse_date_range(start_date, end_date)
    except ValueError:
        return error_response(message="Invalid date format")

    details = await service.get_doctor_details_data(doctor_id, start, end)
    if not details:
        return error_response(message="Doctor not found", status_code=404)

    return success_response(data=details, message="Doctor details retrieved successfully")


@router.put("/staff-compensation/{user_id}", response_model=StandardResponse[dict])
async def update_staff_compensation(
    user_id: int,
    commission_percent: float = 0.0,
    fixed_salary: float = 0.0,
    per_appointment_fee: float = 0.0,
    db: AsyncSession = Depends(get_async_db),
    current_user: schemas.User = Depends(require_permission(Permission.SYSTEM_CONFIG)),
):
    """Update compensation settings for a staff member."""
    service = AccountingService(db, current_user.tenant_id)
    success = await service.update_staff_compensation_settings(
        user_id, current_user, commission_percent, fixed_salary, per_appointment_fee
    )

    if not success:
        return error_response(message="User not found", status_code=404)

    return success_response(data=None, message="Compensation updated")


@router.get("/staff-revenue", response_model=StandardResponse[dict])
async def get_staff_revenue(
    start_date: str = Query(..., description="Start date (YYYY-MM-DD)"),
    end_date: str = Query(..., description="End date (YYYY-MM-DD)"),
    db: AsyncSession = Depends(get_async_db),
    current_user: schemas.User = Depends(require_permission(Permission.FINANCIAL_READ)),
):
    """Get revenue for non-doctor staff (assistants, receptionists, etc.)."""
    # Note: date range logic was in original but unused for listing staff.
    # Just validating date format to keep API consistent.
    service = AccountingService(db, current_user.tenant_id)
    try:
        service.parse_date_range(start_date, end_date)
    except ValueError:
        return error_response(message="Invalid date format", details={"staff": []})

    staff_list = await service.get_staff_list_revenue()
    return success_response(data={"staff": staff_list}, message="Staff revenue retrieved successfully")


@router.get("/comprehensive-stats", response_model=StandardResponse[dict])
async def get_comprehensive_stats(
    start_date: str = Query(..., description="Start date (YYYY-MM-DD)"),
    end_date: str = Query(..., description="End date (YYYY-MM-DD)"),
    db: AsyncSession = Depends(get_async_db),
    current_user: schemas.User = Depends(require_permission(Permission.FINANCIAL_READ)),
):
    """
    Get comprehensive financial statistics with automatic deductions.
    """
    service = AccountingService(db, current_user.tenant_id)
    try:
        start, end = service.parse_date_range(start_date, end_date)
    except ValueError:
        return error_response(message="Invalid date format")

    # 1. Basic Income Stats
    total_income = await service.get_total_income(start, end)
    total_collected = await service.get_total_collected(start, end)

    # 2a. Get Appointments Count (for staff dues calculation)
    total_appointments_stmt = (
        select(func.count(models.Treatment.id))
        .join(models.Patient, models.Treatment.patient_id == models.Patient.id)
        .where(
            models.Patient.tenant_id == current_user.tenant_id,
            models.Patient.is_deleted == False,  # noqa: E712
            models.Treatment.date >= start,
            models.Treatment.date <= end,
        )
    )
    total_appointments = (await db.execute(total_appointments_stmt)).scalar() or 0

    # 2b. Get Unique Patients Count (for UI display)
    unique_patients_stmt = (
        select(func.count(models.Treatment.patient_id.distinct()))
        .join(models.Patient, models.Treatment.patient_id == models.Patient.id)
        .where(
            models.Patient.tenant_id == current_user.tenant_id,
            models.Patient.is_deleted == False,  # noqa: E712
            models.Treatment.date >= start,
            models.Treatment.date <= end,
        )
    )
    unique_patients_count = (await db.execute(unique_patients_stmt)).scalar() or 0

    # 3. Dues & Expenses
    doctor_dues, total_doctor_dues = await service.calculate_doctor_dues(start, end)
    staff_dues, total_staff_dues = await service.calculate_staff_dues(
        start, end, total_appointments
    )

    total_expenses = await service.get_total_expenses(start, end)
    total_lab_costs = await service.get_total_lab_costs(start, end)

    # 4. Net Profit
    # Net Profit = Collected (Cash In) - Expenses (Cash Out)
    net_profit = (
        float(total_collected)
        - float(total_doctor_dues)
        - float(total_staff_dues)
        - float(total_expenses)
        - float(total_lab_costs)
    )

    # 5. ALL TIME Outstanding (Total Debt)
    # The user wants "Remaining" to be the actual debt, not period math.
    all_time_stats = await billing_crud.get_financial_stats(db, current_user.tenant_id)
    real_outstanding = all_time_stats["outstanding"]

    return success_response(data={
        "period": {"start": start_date, "end": end_date},
        "income": {
            "total_revenue": float(total_income),
            "total_collected": float(total_collected),
            "outstanding": float(real_outstanding),  # FIXED: Show actual total debt
            "total_appointments": unique_patients_count,  # Returning unique patients as requested (keeping key name compatible if frontend expects it, or better rename it)
            "unique_patients": unique_patients_count,
        },
        "deductions": {
            "doctor_dues": {"total": float(total_doctor_dues), "details": doctor_dues},
            "staff_dues": {"total": float(total_staff_dues), "details": staff_dues},
            "lab_costs": float(total_lab_costs),
            "expenses": float(total_expenses),
            "total_deductions": float(total_doctor_dues)
            + float(total_staff_dues)
            + float(total_expenses),
        },
        "net_profit": net_profit,
    }, message="Comprehensive stats retrieved successfully")


@router.get("/salaries", response_model=StandardResponse[dict])
async def get_salaries_status(
    month: str = Query(..., description="Month in format YYYY-MM"),
    db: AsyncSession = Depends(get_async_db),
    current_user: schemas.User = Depends(require_permission(Permission.FINANCIAL_READ)),
):
    """
    Get salary payment status for all employees for a specific month.
    """
    service = AccountingService(db, current_user.tenant_id)
    try:
        status_data = await service.get_salary_status_for_month(month)
        return success_response(data=status_data, message="Salaries status retrieved")
    except ValueError:
        return error_response(message="Invalid month format. Use YYYY-MM")


@router.post("/salaries", response_model=StandardResponse[dict])
async def record_salary_payment(
    user_id: int,
    month: str = Query(..., description="Month in format YYYY-MM"),
    amount: float = 0.0,
    is_partial: bool = False,
    days_worked: int = None,
    notes: str = None,
    db: AsyncSession = Depends(get_async_db),
    current_user: schemas.User = Depends(require_permission(Permission.FINANCIAL_WRITE)),
):
    """Record a salary payment for an employee."""
    service = AccountingService(db, current_user.tenant_id)
    result = await service.process_salary_payment(
        user_id, current_user, month, amount, is_partial, days_worked, notes
    )
    if "error" in result:
        return error_response(message=result["error"], status_code=400)

    return success_response(
        data={"payment_id": result["payment_id"]},
        message="تم تسجيل الدفع بنجاح"
    )


@router.delete("/salaries/{payment_id}", response_model=StandardResponse[dict])
async def delete_salary_payment(
    payment_id: int,
    db: AsyncSession = Depends(get_async_db),
    current_user: schemas.User = Depends(require_permission(Permission.FINANCIAL_WRITE)),
):
    """Delete/Cancel a salary payment record."""
    service = AccountingService(db, current_user.tenant_id)
    success = await service.remove_salary_payment(payment_id, current_user)

    if not success:
        return error_response(message="لم يتم العثور على سجل الدفع", status_code=404)

    return success_response(data=None, message="تم حذف سجل الدفع")


@router.put("/staff/{user_id}/hire-date", response_model=StandardResponse[dict])
async def update_hire_date(
    user_id: int,
    hire_date: str = Query(..., description="Hire date in format YYYY-MM-DD"),
    db: AsyncSession = Depends(get_async_db),
    current_user: schemas.User = Depends(require_permission(Permission.SYSTEM_CONFIG)),
):
    """Update the hire date for an employee."""
    service = AccountingService(db, current_user.tenant_id)
    success = await service.update_employee_hire_date(user_id, hire_date, current_user)

    if not success:
        return error_response(message="حدث خطأ. تأكد من وجود الموظف وصحة التاريخ (YYYY-MM-DD)", status_code=400)

    return success_response(data=None, message="تم تحديث تاريخ بداية العمل")
