export const TOOTH_LIFECYCLE_CODES = Object.freeze({
    PRESENT: 'PRESENT',
    MISSING: 'MISSING',
    EXTRACTED: 'EXTRACTED',
    IMPACTED: 'IMPACTED',
    UNERUPTED: 'UNERUPTED',
});

export const FINDING_CODES = Object.freeze({
    CARIES: 'CARIES',
    FRACTURE: 'FRACTURE',
    PAIN: 'PAIN',
});

export const PROCEDURE_CODES = Object.freeze({
    REST_COMPOSITE: 'REST_COMPOSITE',
    ENDO_RCT: 'ENDO_RCT',
    PROS_CROWN: 'PROS_CROWN',
    PROS_BRIDGE: 'PROS_BRIDGE',
    IMPLANT_FIXTURE: 'IMPLANT_FIXTURE',
    IMPLANT_CROWN: 'IMPLANT_CROWN',
    SURG_EXTRACTION: 'SURG_EXTRACTION',
});
