from sqlalchemy.orm import Session
from sqlalchemy import func
from datetime import datetime, date
from backend import models, schemas
from .patient import get_patient


# --- Treatment CRUD ---
def create_treatment(
    db: Session,
    treatment: schemas.TreatmentCreate,
    tenant_id: int = None,
    doctor_id: int = None,
    price_list_id: int = None,
    unit_price: float = None,
    price_snapshot: str = None,
    commit: bool = True,
):
    """
    Create a treatment record.
    If doctor_id or tenant_id are not provided in the schema, they will be auto-filled from parameters.
    """
    treatment_dict = treatment.dict()

    # Remove fields that are not part of the Treatment model
    treatment_dict.pop("consumedMaterials", None)

    # Auto-fill doctor_id if not provided
    if not treatment_dict.get("doctor_id") and doctor_id:
        treatment_dict["doctor_id"] = doctor_id

    # Auto-fill tenant_id if not provided
    if not treatment_dict.get("tenant_id") and tenant_id:
        treatment_dict["tenant_id"] = tenant_id

    # Handle pricing fields if passed in kwargs or dict
    # (FastAPI Pydantic models filter extra fields, so we need to ensure
    # the dictionary has them if they were computed in the router)
    # The router handles this by NOT passing them in 'treatment' schema
    # but we can accept them as extra args or assume they are in the schema if we updated it.
    # Since we didn't update schema, we will receive them via the model if we pass **kwargs
    # but here we construct model from dict.

    # To fix this properly, let's allow extra kwargs to flow into the model
    # OR explicit args.

    db_treatment = models.Treatment(**treatment_dict)

    if price_list_id:
        db_treatment.price_list_id = price_list_id
    if unit_price is not None:
        db_treatment.unit_price = unit_price
    if price_snapshot:
        db_treatment.price_snapshot = price_snapshot

    # Explicitly set pricing fields if they exist in treatment_dict (if schema was updated)
    # OR if we want to support passing them from somewhere.
    # But wait, the router calls: crud.create_treatment(db, treatment, ...)
    # The 'treatment' is a Pydantic model which DOES NOT have unit_price/price_snapshot yet.
    # We must update the Pydantic Schema OR pass them separately.

    # Let's update this function to accept optional price args
    pass
    pass
    db.add(db_treatment)
    if commit:
        db.commit()
        db.refresh(db_treatment)
    else:
        db.flush()
        db.refresh(db_treatment)
    return db_treatment


def get_doctor_revenue(
    db: Session, doctor_id: int, start_date: datetime, end_date: datetime
):
    # Calculate total revenue generated by a doctor
    query = db.query(
        func.sum(models.Treatment.cost - models.Treatment.discount).label("revenue"),
        func.count(models.Treatment.id).label("treatment_count"),
    ).filter(
        models.Treatment.doctor_id == doctor_id,
        models.Treatment.date >= start_date,
        models.Treatment.date <= end_date,
        models.Patient.is_deleted == False,
    )
    result = query.first()
    return {
        "revenue": result.revenue or 0.0,
        "treatment_count": result.treatment_count or 0,
    }


def get_treatments(db: Session, patient_id: int, tenant_id: int):
    # 1. Fetch treatments
    treatments = (
        db.query(models.Treatment)
        .join(models.Patient)
        .filter(
            models.Treatment.patient_id == patient_id,
            models.Patient.tenant_id == tenant_id,
            models.Patient.is_deleted == False,
        )
        .all()
    )

    if not treatments:
        return []

    # 2. Reconstruct Consumed Materials from Stock Movements
    # Collect IDs for batch query
    treatment_ids = [str(t.id) for t in treatments]
    reference_ids = [f"TREATMENT:{tid}" for tid in treatment_ids]

    if not reference_ids:
        return treatments

    try:
        from sqlalchemy.orm import joinedload

        # Fetch all movements linked to these treatments
        movements = (
            db.query(models.StockMovement)
            .filter(models.StockMovement.reference_id.in_(reference_ids))
            .join(models.StockItem)
            .join(models.Batch)
            .join(models.Material)
            .options(
                joinedload(models.StockMovement.stock_item)
                .joinedload(models.StockItem.batch)
                .joinedload(models.Batch.material)
            )
            .all()
        )

        # Map movements to treatment_id
        movements_map = {}  # treatment_id -> { material_id: quantity }

        for m in movements:
            try:
                # Parse reference_id "TREATMENT:123"
                parts = m.reference_id.split(":")
                if len(parts) < 2:
                    continue

                t_id = int(parts[1])

                # Use batch material
                mat_id = m.stock_item.batch.material_id
                qty = abs(m.change_amount)

                if t_id not in movements_map:
                    movements_map[t_id] = {}

                # Aggregate quantity for same material
                if mat_id in movements_map[t_id]:
                    movements_map[t_id][mat_id] += qty
                else:
                    movements_map[t_id][mat_id] = qty

            except Exception:
                # print(f"Error parsing movement {m.id}: {e}")
                continue

        # Attach list to treatment objects
        # We need to construct objects compatible with schemas.ConsumedMaterialItem
        # Pydantic will serialize generic dicts/objects if attributes match
        from backend.schemas.clinical import ConsumedMaterialItem

        for t in treatments:
            if t.id in movements_map:
                # Convert dict {mat_id: qty} to list of objects
                items = []
                for mat_id, qty in movements_map[t.id].items():
                    # We can pass simple dicts if Pydantic config allows, otherwise instantiation
                    items.append(ConsumedMaterialItem(material_id=mat_id, quantity=qty))

                # Create a temporary attribute on the ORM object
                # This works because Pydantic `from_attributes=True` reads it
                t.consumedMaterials = items
            else:
                t.consumedMaterials = []

    except Exception as e:
        print(f"Error reconstruction consumed materials: {e}")
        # Return treatments anyway to avoid crashing listing
        pass

    return treatments


def delete_treatment(db: Session, treatment_id: int, tenant_id: int):
    db_obj = (
        db.query(models.Treatment)
        .join(models.Patient)
        .filter(
            models.Treatment.id == treatment_id, models.Patient.tenant_id == tenant_id
        )
        .first()
    )
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj


def update_treatment(
    db: Session,
    treatment_id: int,
    treatment: schemas.TreatmentCreate,
    tenant_id: int,
    commit: bool = True,
):
    db_treatment = (
        db.query(models.Treatment)
        .join(models.Patient)
        .filter(
            models.Treatment.id == treatment_id, models.Patient.tenant_id == tenant_id
        )
        .first()
    )
    if db_treatment:
        treatment_dict = treatment.dict()
        # Remove fields that are not part of the Treatment model
        treatment_dict.pop("consumedMaterials", None)
        # Preserve doctor_id if not provided in update
        if not treatment_dict.get("doctor_id") and db_treatment.doctor_id:
            treatment_dict["doctor_id"] = db_treatment.doctor_id
        # Ensure tenant_id is set
        if not treatment_dict.get("tenant_id"):
            treatment_dict["tenant_id"] = tenant_id

        for key, value in treatment_dict.items():
            setattr(db_treatment, key, value)
        for key, value in treatment_dict.items():
            setattr(db_treatment, key, value)

        if commit:
            db.commit()
            db.refresh(db_treatment)
        else:
            db.flush()
            db.refresh(db_treatment)
        return db_treatment


# --- Payment CRUD ---
def create_payment(
    db: Session, payment: schemas.PaymentCreate, tenant_id: int, doctor_id: int = None
):
    """
    Create a payment record.
    If doctor_id is not provided, it will be auto-assigned from the patient's most recent treatment.
    """
    patient = get_patient(db, payment.patient_id, tenant_id)
    if not patient:
        return None

    payment_dict = payment.dict()

    # Auto-assign doctor_id if not provided - get from most recent treatment
    if not payment_dict.get("doctor_id") and not doctor_id:
        # Find most recent treatment for this patient
        recent_treatment = (
            db.query(models.Treatment)
            .filter(
                models.Treatment.patient_id == payment.patient_id,
                models.Treatment.doctor_id.isnot(None),
            )
            .order_by(models.Treatment.date.desc())
            .first()
        )
        if recent_treatment:
            doctor_id = recent_treatment.doctor_id

    # Set doctor_id if available
    if doctor_id and not payment_dict.get("doctor_id"):
        payment_dict["doctor_id"] = doctor_id

    # Ensure tenant_id is set
    if not payment_dict.get("tenant_id"):
        payment_dict["tenant_id"] = tenant_id

    db_payment = models.Payment(**payment_dict)
    db.add(db_payment)
    db.commit()
    db.refresh(db_payment)
    return db_payment


def get_payments(db: Session, patient_id: int, tenant_id: int):
    return (
        db.query(models.Payment)
        .join(models.Patient)
        .filter(
            models.Payment.patient_id == patient_id,
            models.Patient.tenant_id == tenant_id,
            models.Patient.is_deleted == False,
        )
        .all()
    )


def get_all_payments(db: Session, tenant_id: int, skip: int = 0, limit: int = 100):
    results = (
        db.query(models.Payment, models.Patient.name)
        .join(models.Patient, models.Payment.patient_id == models.Patient.id)
        .filter(
            models.Patient.tenant_id == tenant_id, models.Patient.is_deleted == False
        )
        # Payment soft delete if implemented, otherwise just rely on Patient
        # .filter(models.Payment.is_deleted == False)
        .order_by(models.Payment.date.desc())
        .offset(skip)
        .limit(limit)
        .all()
    )

    payments = []
    for pay, name in results:
        # Attach name to the payment object for the schema
        pay.patient_name = name
        payments.append(pay)
    return payments


def delete_payment(db: Session, payment_id: int, tenant_id: int):
    db_obj = (
        db.query(models.Payment)
        .join(models.Patient)
        .filter(models.Payment.id == payment_id, models.Patient.tenant_id == tenant_id)
        .first()
    )
    if db_obj:
        db.delete(db_obj)
        db.commit()
    return db_obj


# --- Expenses ---
def create_expense(db: Session, expense: schemas.ExpenseCreate, tenant_id: int):
    db_expense = models.Expense(**expense.dict(), tenant_id=tenant_id)
    db.add(db_expense)
    db.commit()
    db.refresh(db_expense)
    return db_expense


def get_expenses(db: Session, tenant_id: int, skip: int = 0, limit: int = 100):
    return (
        db.query(models.Expense)
        .filter(models.Expense.tenant_id == tenant_id)
        .order_by(models.Expense.date.desc())
        .offset(skip)
        .limit(limit)
        .all()
    )


def delete_expense(db: Session, expense_id: int, tenant_id: int):
    expense = (
        db.query(models.Expense)
        .filter(models.Expense.id == expense_id, models.Expense.tenant_id == tenant_id)
        .first()
    )
    if expense:
        db.delete(expense)
    db.commit()
    return expense


# --- Statistics ---
def get_financial_stats(db: Session, tenant_id: int, doctor_id: int = None):
    """
    Get financial statistics for a tenant.
    """

    today_start = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)

    # Treatments - all time
    treatments_query = (
        db.query(func.sum(models.Treatment.cost))
        .join(models.Patient)
        .filter(
            models.Patient.tenant_id == tenant_id, models.Patient.is_deleted == False
        )
    )

    if doctor_id:
        treatments_query = treatments_query.filter(
            models.Treatment.doctor_id == doctor_id
        )

    total_treatments = treatments_query.scalar() or 0.0
    discounts_query = (
        db.query(func.sum(models.Treatment.discount))
        .join(models.Patient)
        .filter(
            models.Patient.tenant_id == tenant_id, models.Patient.is_deleted == False
        )
    )

    if doctor_id:
        discounts_query = discounts_query.filter(
            models.Treatment.doctor_id == doctor_id
        )

    total_discounts = discounts_query.scalar() or 0.0
    total_revenue = float(total_treatments) - float(total_discounts)

    # Treatments - today
    # Treatments - today
    today_revenue_query = (
        db.query(func.sum(models.Treatment.cost - models.Treatment.discount))
        .join(models.Patient)
        .filter(
            models.Patient.tenant_id == tenant_id,
            models.Patient.is_deleted == False,
            models.Treatment.date >= today_start,
        )
    )

    if doctor_id:
        today_revenue_query = today_revenue_query.filter(
            models.Treatment.doctor_id == doctor_id
        )

    today_revenue = today_revenue_query.scalar() or 0.0
    today_revenue = float(today_revenue)

    # Payments - all time
    payments_query = (
        db.query(func.sum(models.Payment.amount))
        .join(models.Patient)
        .filter(
            models.Patient.tenant_id == tenant_id, models.Patient.is_deleted == False
        )
    )

    if doctor_id:
        payments_query = payments_query.filter(models.Payment.doctor_id == doctor_id)

    total_received = payments_query.scalar() or 0.0
    total_received = float(total_received)

    # Payments - today
    # Payments - today
    today_received_query = (
        db.query(func.sum(models.Payment.amount))
        .join(models.Patient)
        .filter(
            models.Patient.tenant_id == tenant_id,
            models.Patient.is_deleted == False,
            models.Payment.date >= today_start,
        )
    )

    if doctor_id:
        today_received_query = today_received_query.filter(
            models.Payment.doctor_id == doctor_id
        )

    today_received = today_received_query.scalar() or 0.0
    today_received = float(today_received)

    outstanding = total_revenue - total_received
    today_outstanding = max(0, today_revenue - today_received)

    # Lab costs - all time
    lab_costs_query = (
        db.query(func.sum(models.LabOrder.cost))
        .join(models.Patient)
        .filter(
            models.LabOrder.tenant_id == tenant_id, models.Patient.is_deleted == False
        )
    )

    if doctor_id:
        lab_costs_query = lab_costs_query.filter(models.LabOrder.doctor_id == doctor_id)

    total_lab_costs = lab_costs_query.scalar() or 0.0
    total_lab_costs = float(total_lab_costs)

    # Lab costs - today
    # Lab costs - today
    today_lab_costs_query = (
        db.query(func.sum(models.LabOrder.cost))
        .join(models.Patient)
        .filter(
            models.LabOrder.tenant_id == tenant_id,
            models.LabOrder.order_date >= today_start,
            models.Patient.is_deleted == False,
        )
    )

    if doctor_id:
        today_lab_costs_query = today_lab_costs_query.filter(
            models.LabOrder.doctor_id == doctor_id
        )

    today_lab_costs = today_lab_costs_query.scalar() or 0.0
    today_lab_costs = float(today_lab_costs)

    # Expenses - all time
    if doctor_id:
        total_expenses = 0.0
    else:
        total_expenses = (
            db.query(func.sum(models.Expense.cost))
            .filter(models.Expense.tenant_id == tenant_id)
            .scalar()
            or 0.0
        )
    total_expenses = float(total_expenses)

    # Expenses - today
    if doctor_id:
        today_expenses = 0.0
    else:
        today_expenses = (
            db.query(func.sum(models.Expense.cost))
            .filter(
                models.Expense.tenant_id == tenant_id,
                models.Expense.date == date.today(),
            )
            .scalar()
            or 0.0
        )
    today_expenses = float(today_expenses)

    # Net Profit = Received - Expenses - Lab Costs
    net_profit = total_received - total_expenses - total_lab_costs

    return {
        "total_revenue": total_revenue,
        "total_received": total_received,
        "outstanding": outstanding if outstanding > 0 else 0,
        "total_expenses": total_expenses + total_lab_costs,
        "net_profit": net_profit,
        "monthly_revenue": 0.0,
        "today_revenue": today_revenue,
        "today_received": today_received,
        "today_outstanding": today_outstanding,
        "today_expenses": today_expenses + today_lab_costs,
    }


def get_dashboard_stats(db: Session, tenant_id: int, doctor_id: int = None):
    # Reuse financial stats logic
    fin_stats = get_financial_stats(db, tenant_id, doctor_id)

    # 1. Total Patients Count (O(1) with optimized count)
    # We can't easily get current_user here, but if doctor_id is passed, we can filter.
    # However, patients filtering is complex (via visibility service).
    # For now, if doctor_id passed, simpler filtering "Allocated to this doctor"?
    # Or count only Assigned?

    patients_query = db.query(func.count(models.Patient.id)).filter(
        models.Patient.tenant_id == tenant_id, models.Patient.is_deleted == False
    )
    if doctor_id:
        # Strict mode: Only assigned patients
        patients_query = patients_query.filter(
            models.Patient.assigned_doctor_id == doctor_id
        )

    total_patients = patients_query.scalar() or 0

    # 2. Today's Appointments Count
    today_start = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)

    # 2. New Patients Today
    new_patients_query = db.query(func.count(models.Patient.id)).filter(
        models.Patient.tenant_id == tenant_id,
        models.Patient.is_deleted == False,
        func.date(models.Patient.created_at) == func.date(today_start),
    )

    if doctor_id:
        new_patients_query = new_patients_query.filter(
            models.Patient.assigned_doctor_id == doctor_id
        )

    new_patients_today = new_patients_query.scalar() or 0

    # 3. Today's Appointments Count
    appointments_query = (
        db.query(func.count(models.Appointment.id))
        .join(models.Patient)
        .filter(
            models.Patient.tenant_id == tenant_id,
            models.Patient.is_deleted == False,
            models.Appointment.is_deleted == False,
            models.Appointment.status != "Cancelled",  # FIX: Exclude cancelled
            func.date(models.Appointment.date_time) == func.date(today_start),
        )
    )

    if doctor_id:
        appointments_query = appointments_query.filter(
            models.Appointment.doctor_id == doctor_id
        )

    total_appointments_today = appointments_query.scalar() or 0

    # 4. Revenue Chart (Last 7 Days)
    from datetime import timedelta

    chart_data = []
    for i in range(6, -1, -1):
        day = today_start - timedelta(days=i)
        next_day = day + timedelta(days=1)

        daily_rev_query = (
            db.query(func.sum(models.Payment.amount))
            .join(models.Patient)
            .filter(
                models.Patient.tenant_id == tenant_id,
                models.Patient.is_deleted == False,
                models.Payment.date >= day,
                models.Payment.date < next_day,
            )
        )

        if doctor_id:
            daily_rev_query = daily_rev_query.filter(
                models.Payment.doctor_id == doctor_id
            )

        daily_rev = daily_rev_query.scalar() or 0.0
        chart_data.append(
            {"name": day.strftime("%Y-%m-%d"), "revenue": float(daily_rev)}
        )

    return {
        **fin_stats,
        "total_patients": total_patients,
        "new_patients_today": new_patients_today,
        "total_appointments_today": total_appointments_today,
        "revenue_chart": chart_data,
    }
