import asyncio
import logging
from datetime import datetime, date, timezone, timedelta
from sqlalchemy import func, select, cast, case, Date as SADate
from sqlalchemy.orm import joinedload, selectinload
from sqlalchemy.ext.asyncio import AsyncSession
from backend import models, schemas
from backend.services.cache_service import invalidate_dashboard_cache
from .patient import get_patient

logger = logging.getLogger(__name__)


# --- Treatment CRUD ---
async def create_treatment(
    db: AsyncSession,
    treatment: schemas.TreatmentCreate,
    tenant_id: int = None,
    doctor_id: int = None,
    price_list_id: int = None,
    unit_price: float = None,
    price_snapshot: str = None,
    commit: bool = True,
):
    """
    Create a treatment record.
    If doctor_id or tenant_id are not provided in the schema, they will be auto-filled from parameters.
    """
    treatment_dict = treatment.dict()

    # Remove fields that are not part of the Treatment model
    treatment_dict.pop("consumedMaterials", None)
    treatment_dict.pop("skip_stock_check", None)

    # Auto-fill doctor_id if not provided
    if not treatment_dict.get("doctor_id") and doctor_id:
        treatment_dict["doctor_id"] = doctor_id

    # Auto-fill tenant_id if not provided
    if not treatment_dict.get("tenant_id") and tenant_id:
        treatment_dict["tenant_id"] = tenant_id

    db_treatment = models.Treatment(**treatment_dict)

    if price_list_id:
        db_treatment.price_list_id = price_list_id
    if unit_price is not None:
        db_treatment.unit_price = unit_price
    if price_snapshot:
        db_treatment.price_snapshot = price_snapshot

    db.add(db_treatment)
    if commit:
        await db.commit()
        # REGRESSION (2026-06-19): Eager-load treatment_sessions before
        # returning the ORM object, otherwise Pydantic's response
        # serialization of schemas.Treatment.treatment_sessions
        # (Optional[list[TreatmentSession]]) will lazy-load outside the
        # greenlet context and raise MissingGreenlet.
        await db.refresh(
            db_treatment,
            attribute_names=["treatment_sessions"],
        )
    else:
        await db.flush()
        await db.refresh(
            db_treatment,
            attribute_names=["treatment_sessions"],
        )
    return db_treatment


async def get_doctor_revenue(
    db: AsyncSession, doctor_id: int, start_date: datetime, end_date: datetime
):
    # Calculate total revenue generated by a doctor
    stmt = (
        select(
            func.sum(models.Treatment.cost - models.Treatment.discount).label("revenue"),
            func.count(models.Treatment.id).label("treatment_count"),
        )
        .join(models.Patient, models.Treatment.patient_id == models.Patient.id)
        .where(
            models.Treatment.doctor_id == doctor_id,
            models.Treatment.date >= start_date,
            models.Treatment.date <= end_date,
            models.Patient.is_deleted == False,  # noqa: E712
        )
    )
    result = await db.execute(stmt)
    row = result.first()
    return {
        "revenue": row.revenue or 0.0 if row else 0.0,
        "treatment_count": row.treatment_count or 0 if row else 0,
    }


async def get_treatments(db: AsyncSession, patient_id: int, tenant_id: int):
    # 1. Fetch treatments
    stmt = (
        select(models.Treatment)
        .join(models.Patient)
        .where(
            models.Treatment.patient_id == patient_id,
            models.Patient.tenant_id == tenant_id,
            models.Patient.is_deleted == False,  # noqa: E712
        )
        .options(selectinload(models.Treatment.treatment_sessions))
    )
    result = await db.execute(stmt)
    treatments = result.scalars().all()

    if not treatments:
        return []

    # 2. Reconstruct Consumed Materials from Stock Movements
    # Collect IDs for batch query
    treatment_ids = [str(t.id) for t in treatments]
    reference_ids = [f"TREATMENT:{tid}" for tid in treatment_ids]

    if not reference_ids:
        return treatments

    try:
        # Fetch all movements linked to these treatments
        stmt_m = (
            select(models.StockMovement)
            .where(models.StockMovement.reference_id.in_(reference_ids))
            .join(models.StockItem)
            .join(models.Batch)
            .join(models.Material)
            .options(
                joinedload(models.StockMovement.stock_item)
                .joinedload(models.StockItem.batch)
                .joinedload(models.Batch.material)
            )
        )
        result_m = await db.execute(stmt_m)
        movements = result_m.scalars().all()

        # Map movements to treatment_id
        movements_map = {}  # treatment_id -> { material_id: quantity }

        for m in movements:
            try:
                # Parse reference_id "TREATMENT:123"
                parts = m.reference_id.split(":")
                if len(parts) < 2:
                    continue

                t_id = int(parts[1])

                # Use batch material
                mat_id = m.stock_item.batch.material_id
                qty = abs(m.change_amount)

                if t_id not in movements_map:
                    movements_map[t_id] = {}

                # Aggregate quantity for same material
                if mat_id in movements_map[t_id]:
                    movements_map[t_id][mat_id] += qty
                else:
                    movements_map[t_id][mat_id] = qty

            except Exception:
                continue

        # Attach list to treatment objects
        # We need to construct objects compatible with schemas.ConsumedMaterialItem
        # Pydantic will serialize generic dicts/objects if attributes match
        from backend.schemas.clinical import ConsumedMaterialItem

        for t in treatments:
            if t.id in movements_map:
                # Convert dict {mat_id: qty} to list of objects
                items = []
                for mat_id, qty in movements_map[t.id].items():
                    items.append(ConsumedMaterialItem(material_id=mat_id, quantity=qty))

                # Create a temporary attribute on the ORM object
                # This works because Pydantic `from_attributes=True` reads it
                t.consumedMaterials = items
            else:
                t.consumedMaterials = []

    except Exception as e:
        logger.error("Error reconstructing consumed materials: %s", e)

    return treatments


async def delete_treatment(db: AsyncSession, treatment_id: int, tenant_id: int):
    stmt = (
        select(models.Treatment)
        .join(models.Patient)
        .where(
            models.Treatment.id == treatment_id, models.Patient.tenant_id == tenant_id
        )
    )
    result = await db.execute(stmt)
    db_obj = result.scalars().first()
    if db_obj:
        await db.delete(db_obj)
        await db.commit()
    return db_obj


async def update_treatment(
    db: AsyncSession,
    treatment_id: int,
    treatment: schemas.TreatmentCreate,
    tenant_id: int,
    commit: bool = True,
):
    stmt = (
        select(models.Treatment)
        .join(models.Patient)
        .where(
            models.Treatment.id == treatment_id, models.Patient.tenant_id == tenant_id
        )
    )
    result = await db.execute(stmt)
    db_treatment = result.scalars().first()
    if db_treatment:
        treatment_dict = treatment.dict()
        # Remove fields that are not part of the Treatment model
        treatment_dict.pop("consumedMaterials", None)
        treatment_dict.pop("skip_stock_check", None)
        # Preserve doctor_id if not provided in update
        if not treatment_dict.get("doctor_id") and db_treatment.doctor_id:
            treatment_dict["doctor_id"] = db_treatment.doctor_id
        # Ensure tenant_id is set
        if not treatment_dict.get("tenant_id"):
            treatment_dict["tenant_id"] = tenant_id

        for key, value in treatment_dict.items():
            setattr(db_treatment, key, value)

        if commit:
            await db.commit()
            await db.refresh(db_treatment)
        else:
            await db.flush()
            await db.refresh(db_treatment)
        return db_treatment


# --- Payment CRUD ---
async def create_payment(
    db: AsyncSession, payment: schemas.PaymentCreate, tenant_id: int, doctor_id: int = None, commit: bool = True
):
    """
    Create a payment record.
    If doctor_id is not provided, it will be auto-assigned from the patient's most recent treatment.
    """
    patient = await get_patient(db, payment.patient_id, tenant_id)
    if not patient:
        return None

    payment_dict = payment.dict()

    # Auto-assign doctor_id if not provided - get from most recent treatment
    if not payment_dict.get("doctor_id") and not doctor_id:
        # Find most recent treatment for this patient
        stmt = (
            select(models.Treatment)
            .where(
                models.Treatment.patient_id == payment.patient_id,
                models.Treatment.doctor_id.isnot(None),
            )
            .order_by(models.Treatment.date.desc())
        )
        result = await db.execute(stmt)
        recent_treatment = result.scalars().first()
        if recent_treatment:
            doctor_id = recent_treatment.doctor_id

    # Set doctor_id if available
    if doctor_id and not payment_dict.get("doctor_id"):
        payment_dict["doctor_id"] = doctor_id

    # Ensure tenant_id is set
    if not payment_dict.get("tenant_id"):
        payment_dict["tenant_id"] = tenant_id

    db_payment = models.Payment(**payment_dict)
    db.add(db_payment)
    if commit:
        await db.commit()
        # REGRESSION (2026-06-19): Eager-load patient relationship on the
        # returned Payment. schemas.Payment declares patient_name as
        # an Optional[str] from_attributes field — the underlying
        # @property accesses self.patient.name, which lazy-loads after
        # the route returns and triggers MissingGreenlet during
        # response serialization.
        await db.refresh(
            db_payment,
            attribute_names=["patient"],
        )
        # Touch patient.name while greenlet context is still alive so the
        # @property has a fully-loaded value to return later.
        _ = db_payment.patient.name if db_payment.patient else None
    else:
        await db.flush()
        await db.refresh(
            db_payment,
            attribute_names=["patient"],
        )
        _ = db_payment.patient.name if db_payment.patient else None
    invalidate_dashboard_cache(tenant_id)
    asyncio.create_task(
        precompute_dashboard_cache(tenant_id=tenant_id, db=db)
    )
    return db_payment


async def get_payments(db: AsyncSession, patient_id: int, tenant_id: int):
    stmt = (
        select(models.Payment)
        .join(models.Patient)
        .where(
            models.Payment.patient_id == patient_id,
            models.Patient.tenant_id == tenant_id,
            models.Patient.is_deleted == False,  # noqa: E712
        )
        .options(joinedload(models.Payment.patient))
    )
    result = await db.execute(stmt)
    return result.scalars().all()


async def get_all_payments(db: AsyncSession, tenant_id: int, skip: int = 0, limit: int = 100):
    stmt = (
        select(models.Payment, models.Patient.name)
        .join(models.Patient, models.Payment.patient_id == models.Patient.id)
        .where(
            models.Patient.tenant_id == tenant_id, models.Patient.is_deleted == False  # noqa: E712
        )
        .order_by(models.Payment.date.desc())
        .offset(skip)
        .limit(limit)
    )
    result = await db.execute(stmt)
    results = result.all()

    payments = []
    for pay, name in results:
        # Attach name to the payment object for the schema
        pay.patient_name = name
        payments.append(pay)
    return payments


async def delete_payment(db: AsyncSession, payment_id: int, tenant_id: int):
    stmt = (
        select(models.Payment)
        .join(models.Patient)
        .where(models.Payment.id == payment_id, models.Patient.tenant_id == tenant_id)
    )
    result = await db.execute(stmt)
    db_obj = result.scalars().first()
    if db_obj:
        await db.delete(db_obj)
        await db.commit()
    return db_obj


# --- Expenses ---
async def create_expense(db: AsyncSession, expense: schemas.ExpenseCreate, tenant_id: int):
    db_expense = models.Expense(**expense.dict(), tenant_id=tenant_id)
    db.add(db_expense)
    await db.commit()
    await db.refresh(db_expense)
    return db_expense


async def get_expenses(
    db: AsyncSession,
    tenant_id: int,
    skip: int = 0,
    limit: int = 100,
    search: str = None,
    category: str = None,
    start_date: str = None,
    end_date: str = None,
):
    stmt = select(models.Expense).where(models.Expense.tenant_id == tenant_id)
    if search:
        search_pat = f"%{search}%"
        stmt = stmt.where(
            models.Expense.item_name.ilike(search_pat) |
            models.Expense.notes.ilike(search_pat)
        )
    if category:
        stmt = stmt.where(models.Expense.category == category)
    if start_date:
        try:
            s_d = datetime.strptime(start_date, "%Y-%m-%d").date()
            stmt = stmt.where(models.Expense.date >= s_d)
        except ValueError:
            pass
    if end_date:
        try:
            e_d = datetime.strptime(end_date, "%Y-%m-%d").date()
            stmt = stmt.where(models.Expense.date <= e_d)
        except ValueError:
            pass

    stmt = (
        stmt.order_by(models.Expense.date.desc(), models.Expense.id.desc())
        .offset(skip)
        .limit(limit)
    )
    result = await db.execute(stmt)
    return result.scalars().all()


async def count_expenses(
    db: AsyncSession,
    tenant_id: int,
    search: str = None,
    category: str = None,
    start_date: str = None,
    end_date: str = None,
) -> int:
    """Count expenses using the same tenant-scoped filters as ``get_expenses``."""
    stmt = select(func.count(models.Expense.id)).where(models.Expense.tenant_id == tenant_id)
    if search:
        search_pat = f"%{search}%"
        stmt = stmt.where(
            models.Expense.item_name.ilike(search_pat) |
            models.Expense.notes.ilike(search_pat)
        )
    if category:
        stmt = stmt.where(models.Expense.category == category)
    if start_date:
        try:
            stmt = stmt.where(models.Expense.date >= datetime.strptime(start_date, "%Y-%m-%d").date())
        except ValueError:
            pass
    if end_date:
        try:
            stmt = stmt.where(models.Expense.date <= datetime.strptime(end_date, "%Y-%m-%d").date())
        except ValueError:
            pass

    return int((await db.execute(stmt)).scalar() or 0)


async def delete_expense(db: AsyncSession, expense_id: int, tenant_id: int):
    stmt = (
        select(models.Expense)
        .where(models.Expense.id == expense_id, models.Expense.tenant_id == tenant_id)
    )
    result = await db.execute(stmt)
    expense = result.scalars().first()
    if expense:
        await db.delete(expense)
    await db.commit()
    return expense


# --- Statistics ---
async def precompute_dashboard_cache(tenant_id: int, db: AsyncSession) -> None:
    """
    Silently precompute dashboard stats into cache after invalidation.
    Called as a background task so the next real request hits the cache.
    """
    import os
    if os.getenv("ENVIRONMENT") == "testing":
        return
    try:
        await get_dashboard_stats(db=db, tenant_id=tenant_id)
    except Exception:
        pass  # silent — cache will rebuild on the next real request


async def get_financial_stats(db: AsyncSession, tenant_id: int, doctor_id: int = None):
    """
    Get financial statistics for a tenant.

    Uses 3 batch aggregation queries (CASE WHEN) instead of 9 individual ones:
      Query 1 — Treatment revenue (total cost, total discount, today net revenue)
      Query 2 — Payment totals (all-time and today)
      Query 3 — Lab costs + Expenses (all-time and today)
    """
    today_start = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)

    # ------------------------------------------------------------------
    # Query 1: Treatment revenue — total cost, total discounts, today net
    # ------------------------------------------------------------------
    treatment_base = (
        select(
            func.sum(models.Treatment.cost).label("total_cost"),
            func.sum(models.Treatment.discount).label("total_discount"),
            func.sum(
                case(
                    (models.Treatment.date >= today_start,
                     models.Treatment.cost - models.Treatment.discount),
                    else_=0,
                )
            ).label("today_revenue"),
        )
        .join(models.Patient)
        .where(
            models.Patient.tenant_id == tenant_id,
            models.Patient.is_deleted == False,  # noqa: E712
        )
    )
    if doctor_id:
        treatment_base = treatment_base.where(models.Treatment.doctor_id == doctor_id)

    t_row = (await db.execute(treatment_base)).first()
    total_treatments = float(t_row.total_cost or 0.0)
    total_discounts  = float(t_row.total_discount or 0.0)
    total_revenue    = total_treatments - total_discounts
    today_revenue    = float(t_row.today_revenue or 0.0)

    # ------------------------------------------------------------------
    # Query 2: Payment totals — all-time and today
    # ------------------------------------------------------------------
    payment_base = (
        select(
            func.sum(models.Payment.amount).label("total_received"),
            func.sum(
                case(
                    (models.Payment.date >= today_start, models.Payment.amount),
                    else_=0,
                )
            ).label("today_received"),
        )
        .join(models.Patient)
        .where(
            models.Patient.tenant_id == tenant_id,
            models.Patient.is_deleted == False,  # noqa: E712
        )
    )
    if doctor_id:
        payment_base = payment_base.where(models.Payment.doctor_id == doctor_id)

    p_row = (await db.execute(payment_base)).first()
    total_received = float(p_row.total_received or 0.0)
    today_received = float(p_row.today_received or 0.0)

    # ------------------------------------------------------------------
    # Query 3: Lab costs + Expenses — all-time and today
    # (Expenses are skipped when filtering by doctor_id; lab orders join Patient)
    # ------------------------------------------------------------------
    lab_base = (
        select(
            func.sum(models.LabOrder.cost).label("total_lab"),
            func.sum(
                case(
                    (models.LabOrder.order_date >= today_start, models.LabOrder.cost),
                    else_=0,
                )
            ).label("today_lab"),
        )
        .join(models.Patient)
        .where(
            models.LabOrder.tenant_id == tenant_id,
            models.Patient.is_deleted == False,  # noqa: E712
        )
    )
    if doctor_id:
        lab_base = lab_base.where(models.LabOrder.doctor_id == doctor_id)

    l_row = (await db.execute(lab_base)).first()
    total_lab_costs = float(l_row.total_lab or 0.0)
    today_lab_costs = float(l_row.today_lab or 0.0)

    if doctor_id:
        # Expenses are not doctor-specific; skip when filtering by doctor
        total_expenses = 0.0
        today_expenses = 0.0
    else:
        exp_base = select(
            func.sum(models.Expense.cost).label("total_expenses"),
            func.sum(
                case(
                    (models.Expense.date == date.today(), models.Expense.cost),
                    else_=0,
                )
            ).label("today_expenses"),
        ).where(models.Expense.tenant_id == tenant_id)

        # Expenses query is folded into Query 3 logically but executed as a
        # lightweight single-table aggregate — still just 1 round-trip.
        e_row = (await db.execute(exp_base)).first()
        total_expenses = float(e_row.total_expenses or 0.0)
        today_expenses = float(e_row.today_expenses or 0.0)

    # ------------------------------------------------------------------
    # Derived aggregates
    # ------------------------------------------------------------------
    outstanding       = total_revenue - total_received
    today_outstanding = max(0, today_revenue - today_received)
    net_profit        = total_received - total_expenses - total_lab_costs

    return {
        "total_revenue":    total_revenue,
        "total_received":   total_received,
        "outstanding":      outstanding if outstanding > 0 else 0,
        "total_expenses":   total_expenses + total_lab_costs,
        "net_profit":       net_profit,
        "monthly_revenue":  0.0,
        "today_revenue":    today_revenue,
        "today_received":   today_received,
        "today_outstanding": today_outstanding,
        "today_expenses":   today_expenses + today_lab_costs,
    }


async def get_dashboard_stats(db: AsyncSession, tenant_id: int, doctor_id: int = None):
    # Reuse financial stats logic
    fin_stats = await get_financial_stats(db, tenant_id, doctor_id)

    patients_stmt = select(func.count(models.Patient.id)).where(
        models.Patient.tenant_id == tenant_id,
        models.Patient.is_deleted == False,  # noqa: E712
    )
    if doctor_id:
        patients_stmt = patients_stmt.where(
            models.Patient.assigned_doctor_id == doctor_id
        )

    result = await db.execute(patients_stmt)
    total_patients = result.scalar() or 0

    today_start = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)

    # 2. New Patients Today
    new_patients_stmt = select(func.count(models.Patient.id)).where(
        models.Patient.tenant_id == tenant_id,
        models.Patient.is_deleted == False,  # noqa: E712
        func.date(models.Patient.created_at) == func.date(today_start),
    )

    if doctor_id:
        new_patients_stmt = new_patients_stmt.where(
            models.Patient.assigned_doctor_id == doctor_id
        )

    result = await db.execute(new_patients_stmt)
    new_patients_today = result.scalar() or 0

    # 3. Today's Appointments Count
    appointments_stmt = (
        select(func.count(models.Appointment.id))
        .join(models.Patient)
        .where(
            models.Patient.tenant_id == tenant_id,
            models.Patient.is_deleted == False,  # noqa: E712
            models.Appointment.is_deleted == False,  # noqa: E712
            models.Appointment.status != "Cancelled",  # FIX: Exclude cancelled
            func.date(models.Appointment.date_time) == func.date(today_start),
        )
    )

    if doctor_id:
        appointments_stmt = appointments_stmt.where(
            models.Appointment.doctor_id == doctor_id
        )

    result = await db.execute(appointments_stmt)
    total_appointments_today = result.scalar() or 0

    # 4. Revenue Chart (Last 7 Days)
    chart_start = today_start - timedelta(days=6)
    chart_end   = today_start + timedelta(days=1)

    _rev_stmt = (
        select(
            cast(models.Payment.date, SADate).label("day"),
            func.sum(models.Payment.amount).label("total"),
        )
        .join(models.Patient)
        .where(
            models.Patient.tenant_id == tenant_id,
            models.Patient.is_deleted == False,  # noqa: E712
            models.Payment.date >= chart_start,
            models.Payment.date < chart_end,
        )
        .group_by(cast(models.Payment.date, SADate))
    )
    if doctor_id:
        _rev_stmt = _rev_stmt.where(models.Payment.doctor_id == doctor_id)

    _rev_result = await db.execute(_rev_stmt)
    _rev_by_day = {row.day: float(row.total) for row in _rev_result.fetchall()}

    chart_data = [
        {
            "name": (today_start - timedelta(days=i)).strftime("%Y-%m-%d"),
            "revenue": _rev_by_day.get((today_start - timedelta(days=i)).date(), 0.0),
        }
        for i in range(6, -1, -1)
    ]

    return {
        **fin_stats,
        "total_patients": total_patients,
        "new_patients_today": new_patients_today,
        "total_appointments_today": total_appointments_today,
        "revenue_chart": chart_data,
    }
