"""Add standard_price

Revision ID: 75f8ada5a00f
Revises: 225a616b0b3d
Create Date: 2026-02-01 22:34:13.254992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.core.security


# revision identifiers, used by Alembic.
revision: str = "75f8ada5a00f"
down_revision: Union[str, Sequence[str], None] = "225a616b0b3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('materials', sa.Column('standard_price', sa.Float(), nullable=True))
    op.add_column(
        "patients",
        sa.Column("email", backend.core.security.EncryptedString(), nullable=True),
    )
    op.add_column("patients", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column("patients", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_patients_email"), "patients", ["email"], unique=False)
    op.create_index(op.f("ix_patients_phone"), "patients", ["phone"], unique=False)
    op.add_column(
        "subscription_plans", sa.Column("is_default", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_plans", "is_default")
    op.drop_index(op.f("ix_patients_phone"), table_name="patients")
    op.drop_index(op.f("ix_patients_email"), table_name="patients")
    op.drop_column("patients", "deleted_at")
    op.drop_column("patients", "is_deleted")
    op.drop_column("patients", "email")
    op.drop_column("materials", "standard_price")
    # ### end Alembic commands ###
