"""Add standard_price

Revision ID: 75f8ada5a00f
Revises: 225a616b0b3d
Create Date: 2026-02-01 22:34:13.254992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75f8ada5a00f"
down_revision: Union[str, Sequence[str], None] = "225a616b0b3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use inspector to check for column existence
    from sqlalchemy.engine.reflection import Inspector
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # Patients table columns
    patient_columns = [c["name"] for c in inspector.get_columns("patients")]
    if "email" not in patient_columns:
        op.add_column("patients", sa.Column("email", sa.String(), nullable=True))
    if "is_deleted" not in patient_columns:
        op.add_column("patients", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    if "deleted_at" not in patient_columns:
        op.add_column("patients", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    
    # Patients table indexes
    patient_indexes = [idx["name"] for idx in inspector.get_indexes("patients")]
    if "ix_patients_email" not in patient_indexes:
        op.create_index(op.f("ix_patients_email"), "patients", ["email"], unique=False)
    if "ix_patients_phone" not in patient_indexes:
        op.create_index(op.f("ix_patients_phone"), "patients", ["phone"], unique=False)
    
    # Subscription plans columns
    sub_columns = [c["name"] for c in inspector.get_columns("subscription_plans")]
    if "is_default" not in sub_columns:
        op.add_column("subscription_plans", sa.Column("is_default", sa.Boolean(), nullable=True))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_plans", "is_default")
    op.drop_index(op.f("ix_patients_phone"), table_name="patients")
    op.drop_index(op.f("ix_patients_email"), table_name="patients")
    op.drop_column("patients", "deleted_at")
    op.drop_column("patients", "is_deleted")
    op.drop_column("patients", "email")
    op.drop_column("materials", "standard_price")
    # ### end Alembic commands ###
