"""add_system_errors_table

Revision ID: ceb1e9e1108c
Revises: 
Create Date: 2026-01-30 13:56:59.899268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.core.security # Added this import


# revision identifiers, used by Alembic.
revision: str = 'ceb1e9e1108c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Table and columns already exist in DB, skipping
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'is_default')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_column('patients', 'deleted_at')
    op.drop_column('patients', 'is_deleted')
    op.drop_column('patients', 'email')
    op.drop_column('appointments', 'deleted_at')
    op.drop_column('appointments', 'is_deleted')
    op.drop_index(op.f('ix_system_errors_source'), table_name='system_errors')
    op.drop_index(op.f('ix_system_errors_level'), table_name='system_errors')
    op.drop_index(op.f('ix_system_errors_id'), table_name='system_errors')
    op.drop_table('system_errors')
    # ### end Alembic commands ###
