"""Add missing AI and inventory tables

Revision ID: e0eb7ca469b9
Revises: 75f8ada5a00f
Create Date: 2026-02-07 14:11:22.915614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0eb7ca469b9'
down_revision: Union[str, Sequence[str], None] = '75f8ada5a00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_payments_date'), 'lab_payments', ['date'], unique=False)
    op.create_index(op.f('ix_lab_payments_id'), 'lab_payments', ['id'], unique=False)
    op.create_index(op.f('ix_lab_payments_laboratory_id'), 'lab_payments', ['laboratory_id'], unique=False)
    op.create_index(op.f('ix_lab_payments_tenant_id'), 'lab_payments', ['tenant_id'], unique=False)
    op.alter_column('system_errors', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_system_errors_created_at'), 'system_errors', ['created_at'], unique=False)
    op.drop_constraint(None, 'system_errors', type_='foreignkey')
    op.drop_constraint(None, 'system_errors', type_='foreignkey')
    op.add_column('users', sa.Column('active_session_id', sa.String(), nullable=True))
    
    # Manually added missing tables
    # AILog
    op.create_table('ai_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('trace_id', sa.String(length=50), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('intent', sa.String(length=100), nullable=True),
        sa.Column('tool', sa.String(length=100), nullable=True),
        sa.Column('model', sa.String(length=50), nullable=True),
        sa.Column('input_text', sa.Text(), nullable=True),
        sa.Column('output_text', sa.Text(), nullable=True),
        sa.Column('tool_params', sa.Text(), nullable=True),
        sa.Column('tool_result', sa.Text(), nullable=True),
        sa.Column('execution_time_ms', sa.Integer(), nullable=True),
        sa.Column('tokens_in', sa.Integer(), nullable=True),
        sa.Column('tokens_out', sa.Integer(), nullable=True),
        sa.Column('cost', sa.Float(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('error_type', sa.String(length=50), nullable=True),
        sa.Column('error_details', sa.Text(), nullable=True),
        sa.Column('policy_check', sa.Boolean(), nullable=True),
        sa.Column('scribe_mode', sa.Boolean(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_logs_id'), 'ai_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_logs_trace_id'), 'ai_logs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_tenant_id'), 'ai_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_timestamp'), 'ai_logs', ['timestamp'], unique=False)

    # ProcedureMaterialWeight
    op.create_table('procedure_material_weights',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('procedure_id', sa.Integer(), nullable=False),
        sa.Column('material_id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('weight', sa.Float(), nullable=True),
        sa.Column('current_average_usage', sa.Float(), nullable=True),
        sa.Column('sample_size', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
        sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_material_weights_id'), 'procedure_material_weights', ['id'], unique=False)
    op.create_index(op.f('ix_procedure_material_weights_material_id'), 'procedure_material_weights', ['material_id'], unique=False)
    op.create_index(op.f('ix_procedure_material_weights_procedure_id'), 'procedure_material_weights', ['procedure_id'], unique=False)

    # MaterialLearningLog
    op.create_table('material_learning_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('material_id', sa.Integer(), nullable=False),
        sa.Column('total_consumed', sa.Float(), nullable=False),
        sa.Column('calculation_data', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
        sa.ForeignKeyConstraint(['session_id'], ['material_sessions.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_learning_logs_id'), 'material_learning_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_session_id')
    op.create_foreign_key(None, 'system_errors', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'system_errors', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_system_errors_created_at'), table_name='system_errors')
    op.alter_column('system_errors', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_lab_payments_tenant_id'), table_name='lab_payments')
    op.drop_index(op.f('ix_lab_payments_laboratory_id'), table_name='lab_payments')
    op.drop_index(op.f('ix_lab_payments_id'), table_name='lab_payments')
    op.drop_index(op.f('ix_lab_payments_date'), table_name='lab_payments')
    op.drop_table('lab_payments')
    # ### end Alembic commands ###
