"""Add system error missing columns

Revision ID: e146e0d57b66
Revises: drop_ai_usage_logs
Create Date: 2026-04-18 01:09:41.676819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e146e0d57b66'
down_revision: Union[str, Sequence[str], None] = 'drop_ai_usage_logs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_usage_logs_created_at', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_logs_user_id', table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_constraint('appointments_tenant_id_fkey', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'tenant_id')
    op.drop_index('ix_saved_medications_tenant_id', table_name='saved_medications')
    op.drop_index('ix_support_messages_status', table_name='support_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_support_messages_status', 'support_messages', ['status'], unique=False)
    op.create_index('ix_saved_medications_tenant_id', 'saved_medications', ['tenant_id'], unique=False)
    op.add_column('appointments', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('appointments_tenant_id_fkey', 'appointments', 'tenants', ['tenant_id'], ['id'])
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_tool', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trace_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trace_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='ai_usage_logs_tenant_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_usage_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_usage_logs_pkey')
    )
    op.create_index('ix_ai_usage_logs_user_id', 'ai_usage_logs', ['user_id'], unique=False)
    op.create_index('ix_ai_usage_logs_created_at', 'ai_usage_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
