"""add patient_id and disposal tracking to material_sessions

Revision ID: e21aaee286c0
Revises: ded07d91ace9
Create Date: 2026-05-07 16:53:42.018190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21aaee286c0'
down_revision: Union[str, Sequence[str], None] = 'ded07d91ace9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_sessions', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.add_column('material_sessions', sa.Column('is_disposed', sa.Boolean(), nullable=True))
    op.add_column('material_sessions', sa.Column('disposal_reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_material_sessions_patient_id'), 'material_sessions', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'material_sessions', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_material_sessions_patient_id'), table_name='material_sessions')
    op.drop_column('material_sessions', 'disposal_reason')
    op.drop_column('material_sessions', 'is_disposed')
    op.drop_column('material_sessions', 'patient_id')
    # ### end Alembic commands ###
