"""
DENTIX Clinical VNext - Canonical Catalog and Workflow Blueprint Registry.
Phase G2 implementation: G2-M01 through G2-M16.
"""

from backend.clinical.catalog import (
    ALLOWED_TARGET_KINDS,
    CANONICAL_FINDING_CODES,
    CANONICAL_PROCEDURE_CODES,
    CANONICAL_TOOTH_LIFECYCLE_CODES,
    CANONICAL_TREATMENT_LIFECYCLE_CODES,
    FINDING_DEFINITIONS,
    FROZEN_RENDERER_PROCEDURE_CODES,
    PROCEDURE_CATEGORIES,
    PROCEDURE_DEFINITIONS,
    PROCEDURE_SUBCATEGORIES,
    FindingCode,
    FindingDefinition,
    ProcedureCategory,
    ProcedureCode,
    ProcedureDefinition,
    ProcedureSubcategory,
    TargetKind,
    ToothLifecycleCode,
    TreatmentLifecycleCode,
    get_category,
    get_finding,
    get_procedure,
    get_subcategory,
    is_renderer_supported,
    list_categories,
    list_findings,
    list_procedures,
    list_subcategories,
    validate_finding_targets,
    validate_procedure_targets,
    validate_target_kind,
    validate_tooth_lifecycle,
    validate_treatment_status,
)
from backend.clinical.workflow_templates import (
    CANONICAL_WORKFLOW_TEMPLATES,
    ENDO_RCT_TEMPLATE_V1,
    PROS_BRIDGE_TEMPLATE_V1,
    PROS_CROWN_TEMPLATE_V1,
    PROS_DENTURE_TEMPLATE_V1,
    REST_COMPOSITE_TEMPLATE_V1,
    SURG_EXTRACTION_TEMPLATE_V1,
    WorkflowStepDefinition,
    WorkflowTemplateDefinition,
    WorkflowTemplateRegistry,
    create_default_registry,
    get_latest_template,
    get_template,
    get_workflow_registry,
    list_templates,
)

__all__ = [
    # Catalog codes & enums
    "ToothLifecycleCode",
    "CANONICAL_TOOTH_LIFECYCLE_CODES",
    "FindingCode",
    "CANONICAL_FINDING_CODES",
    "ProcedureCode",
    "CANONICAL_PROCEDURE_CODES",
    "FROZEN_RENDERER_PROCEDURE_CODES",
    "TreatmentLifecycleCode",
    "CANONICAL_TREATMENT_LIFECYCLE_CODES",
    "TargetKind",
    "ALLOWED_TARGET_KINDS",
    # Taxonomy models & collections
    "ProcedureCategory",
    "ProcedureSubcategory",
    "ProcedureDefinition",
    "FindingDefinition",
    "PROCEDURE_CATEGORIES",
    "PROCEDURE_SUBCATEGORIES",
    "PROCEDURE_DEFINITIONS",
    "FINDING_DEFINITIONS",
    # Catalog accessors & validators
    "get_procedure",
    "get_finding",
    "get_category",
    "get_subcategory",
    "list_procedures",
    "list_findings",
    "list_categories",
    "list_subcategories",
    "is_renderer_supported",
    "validate_target_kind",
    "validate_finding_targets",
    "validate_procedure_targets",
    "validate_treatment_status",
    "validate_tooth_lifecycle",
    # Workflow templates
    "WorkflowStepDefinition",
    "WorkflowTemplateDefinition",
    "WorkflowTemplateRegistry",
    "CANONICAL_WORKFLOW_TEMPLATES",
    "ENDO_RCT_TEMPLATE_V1",
    "PROS_CROWN_TEMPLATE_V1",
    "PROS_BRIDGE_TEMPLATE_V1",
    "REST_COMPOSITE_TEMPLATE_V1",
    "SURG_EXTRACTION_TEMPLATE_V1",
    "PROS_DENTURE_TEMPLATE_V1",
    "create_default_registry",
    "get_workflow_registry",
    "get_template",
    "get_latest_template",
    "list_templates",
]
