const createCopy = (copy) => Object.freeze({
    ...copy,
    legend: Object.freeze(copy.legend),
    focusOptions: Object.freeze(copy.focusOptions),
    surfaces: Object.freeze(copy.surfaces),
    quadrants: Object.freeze(copy.quadrants),
});

export const CLINICAL_CHART_LOCALES = Object.freeze({
    AR: 'ar',
    EN: 'en',
});

export const CLINICAL_CHART_COPY = Object.freeze({
    ar: createCopy({
        localeName: 'العربية',
        alternateLocaleName: 'English',
        eyebrow: 'المخطط السريري',
        workspaceTitle: 'مقارنة مخطط الأسنان',
        workspaceDescription: 'قارن الحالة الحالية بلقطة سابقة للعرض فقط دون تغيير البيانات السريرية.',
        readOnly: 'للقراءة فقط',
        currentTitle: 'المخطط الحالي',
        currentSubtitle: 'الحالة الحالية',
        historyTitle: 'المخطط السابق',
        historySubtitle: 'لقطة تاريخية للعرض فقط',
        legendLabel: 'دليل ألوان مخطط الأسنان',
        legend: {
            caries: 'تسوس',
            composite: 'حشو تجميلي',
            endodontic: 'علاج عصب',
            prosthetic: 'تاج أو جسر',
            implant: 'زراعة',
            missing: 'سن مفقود',
        },
        previewFocus: 'تركيز المعاينة',
        showRoots: 'إظهار الجذور',
        roots: 'الجذور',
        showClinicalLayers: 'إظهار الحالات والإجراءات',
        clinicalLayers: 'الحالات والإجراءات',
        focusOptions: {
            none: 'بدون تحديد',
            tooth46Distal: 'السن 46 — السطح البعيد (D)',
            tooth36Occlusal: 'السن 36 — السطح الإطباقي (O)',
        },
        inspector: 'لوحة الفحص',
        previewOnly: 'معاينة فقط',
        selectedTooth: 'السن المحدد',
        selectedSurface: 'السطح المحدد',
        findings: 'الحالات',
        procedures: 'الإجراءات',
        none: 'لا يوجد',
        surfaces: {
            M: 'أنسي (M)',
            D: 'بعيد (D)',
            O: 'إطباقي (O)',
            I: 'قاطع (I)',
            B: 'شدقي (B)',
            L: 'لساني (L)',
            P: 'حنكي (P)',
        },
        mobileQuadrants: 'انتقال سريع بين الأرباع',
        quadrants: {
            upperRight: 'الربع العلوي الأيمن',
            upperLeft: 'الربع العلوي الأيسر',
            lowerRight: 'الربع السفلي الأيمن',
            lowerLeft: 'الربع السفلي الأيسر',
        },
    }),
    en: createCopy({
        localeName: 'English',
        alternateLocaleName: 'العربية',
        eyebrow: 'Clinical chart',
        workspaceTitle: 'Odontogram comparison',
        workspaceDescription: 'Compare the current projection with a read-only historical snapshot without changing clinical data.',
        readOnly: 'Read-only',
        currentTitle: 'Current chart',
        currentSubtitle: 'Current state',
        historyTitle: 'Previous chart',
        historySubtitle: 'Read-only historical snapshot',
        legendLabel: 'Clinical chart legend',
        legend: {
            caries: 'Caries',
            composite: 'Composite',
            endodontic: 'Endodontic therapy',
            prosthetic: 'Crown or bridge',
            implant: 'Implant',
            missing: 'Missing tooth',
        },
        previewFocus: 'Preview focus',
        showRoots: 'Show roots',
        roots: 'Roots',
        showClinicalLayers: 'Show conditions and procedures',
        clinicalLayers: 'Conditions and procedures',
        focusOptions: {
            none: 'None',
            tooth46Distal: 'Tooth 46 — Distal surface (D)',
            tooth36Occlusal: 'Tooth 36 — Occlusal surface (O)',
        },
        inspector: 'Inspector',
        previewOnly: 'Preview only',
        selectedTooth: 'Selected tooth',
        selectedSurface: 'Selected surface',
        findings: 'Findings',
        procedures: 'Procedures',
        none: 'None',
        surfaces: {
            M: 'Mesial (M)',
            D: 'Distal (D)',
            O: 'Occlusal (O)',
            I: 'Incisal (I)',
            B: 'Buccal (B)',
            L: 'Lingual (L)',
            P: 'Palatal (P)',
        },
        mobileQuadrants: 'Quick quadrant navigation',
        quadrants: {
            upperRight: 'Upper-right quadrant',
            upperLeft: 'Upper-left quadrant',
            lowerRight: 'Lower-right quadrant',
            lowerLeft: 'Lower-left quadrant',
        },
    }),
});
